import { Menu } from "@/@types/menu/menu.type";
import { atom } from "jotai";
import { 
  faGauge,
  faUsers,
  faBoxOpen,
  faShoppingCart,
  faChartBar,
  faCog,
  faUserShield,
  faMoneyBillWave,
  faEnvelope,
  faCalendarAlt,
  faBell,
  faFileAlt,
  faDatabase,
  faComments,
  faClipboardList,
  faCreditCard,
  faTruck,
  faHeart,
  faStar,
  faMapMarkerAlt,
  faQuestionCircle,
  faSignOutAlt,
  faFileInvoiceDollar,
  faTags,
  faFolderOpen,
  faWrench,
  faLightbulb,
  faChartPie,
  faBook,
  faUsersCog
} from "@fortawesome/free-solid-svg-icons";

export const openMenuAtom = atom<boolean>(false);
export const selectedMenuAtom = atom<string | null>(null);
export const menuAtom = atom<Menu[]>([
  { name: "Dashboard",       icon: faGauge,           key: "dashboard",       router: "/dashboard" },
  { name: "Clientes",        icon: faUsers,           key: "customers",       router: "/customers" },
  { name: "Produtos",        icon: faBoxOpen,         key: "products",        router: "/products" },
  { name: "Pedidos",         icon: faShoppingCart,    key: "orders",          router: "/orders" },
  { name: "Relatórios",      icon: faChartBar,        key: "reports",         router: "/reports" },
  { name: "Configurações",   icon: faCog,             key: "settings",        router: "/settings" },
  { name: "Usuários",        icon: faUserShield,      key: "users",           router: "/users" },
  { name: "Financeiro",      icon: faMoneyBillWave,   key: "finance",         router: "/finance" },
  { name: "Mensagens",       icon: faEnvelope,        key: "messages",        router: "/messages" },
  { name: "Calendário",      icon: faCalendarAlt,     key: "calendar",        router: "/calendar" },
  { name: "Notificações",    icon: faBell,            key: "notifications",   router: "/notifications" },
  { name: "Documentos",      icon: faFileAlt,         key: "documents",       router: "/documents" },
  { name: "Banco de Dados",  icon: faDatabase,        key: "database",        router: "/database" },
  { name: "Comentários",     icon: faComments,        key: "comments",        router: "/comments" },
  { name: "Tarefas",         icon: faClipboardList,   key: "tasks",           router: "/tasks" },
  { name: "Pagamentos",      icon: faCreditCard,      key: "payments",        router: "/payments" },
  { name: "Entrega",         icon: faTruck,           key: "delivery",        router: "/delivery" },
  { name: "Favoritos",       icon: faHeart,           key: "favorites",       router: "/favorites" },
  { name: "Avaliações",      icon: faStar,            key: "reviews",         router: "/reviews" },
  { name: "Localização",     icon: faMapMarkerAlt,    key: "location",        router: "/location" },
  { name: "Ajuda",           icon: faQuestionCircle,  key: "help",            router: "/help" },
  { name: "Sair",            icon: faSignOutAlt,      key: "logout",          router: "/logout" },
  { name: "Faturas",         icon: faFileInvoiceDollar,key: "invoices",        router: "/invoices" },
  { name: "Etiquetas",       icon: faTags,            key: "tags",            router: "/tags" },
  { name: "Arquivos",        icon: faFolderOpen,      key: "files",           router: "/files" },
  { name: "Ferramentas",     icon: faWrench,          key: "tools",           router: "/tools" },
  { name: "Ideias",          icon: faLightbulb,       key: "ideas",           router: "/ideas" },
  { name: "Análises",        icon: faChartPie,        key: "analytics",       router: "/analytics" },
  { name: "Biblioteca",      icon: faBook,            key: "library",         router: "/library" },
  { name: "Administração",   icon: faUsersCog,        key: "admin",           router: "/admin" },
]);